# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: yotix
open_collective: # Replace with a single Open Collective username
ko_fi: yotix
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: yotix
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
